version: "3.3"

services:
  app:
    image: inspectorio/airflow:1.10.2
    ports:
    - 8080:8080
    - 8793:8793
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_PORT: '5432'

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
